# Generated by Django 4.2.7 on 2025-08-07 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TourPackage',
            new_name='TourPackages',
        ),
    ]
