# Generated by Django 4.2.7 on 2025-08-07 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0002_rename_tourpackage_tourpackages'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('terms', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TourPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tour_photos/')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='adminside.tourpackage')),
            ],
        ),
        migrations.DeleteModel(
            name='TourPackages',
        ),
    ]
