# Generated by Django 4.2.7 on 2025-08-11 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0003_tourpackage_tourphoto_delete_tourpackages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
        migrations.DeleteModel(
            name='CountryCity',
        ),
        migrations.RemoveField(
            model_name='tourphoto',
            name='package',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='TourPackage',
        ),
        migrations.DeleteModel(
            name='TourPhoto',
        ),
    ]
