# Generated by Django 4.2.7 on 2025-08-11 07:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0005_country_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('packagetitle', models.CharField(max_length=255)),
                ('source_country_city', models.CharField(max_length=255)),
                ('destination_country_city', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('terms_and_conditions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TourPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tour_photos/')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='adminside.tourpackage')),
            ],
        ),
    ]
