# Generated by Django 4.2.7 on 2025-08-12 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0007_packageschedule_schedule_schedulephoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='package_schedule',
        ),
        migrations.RemoveField(
            model_name='schedulephoto',
            name='schedule',
        ),
        migrations.DeleteModel(
            name='PackageSchedule',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.DeleteModel(
            name='SchedulePhoto',
        ),
    ]
