# Generated by Django 4.2.7 on 2025-08-12 11:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0008_remove_schedule_package_schedule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schedule_title', models.CharField(max_length=255)),
                ('from_date', models.CharField(max_length=255)),
                ('to_date', models.CharField(max_length=255)),
                ('amount', models.TextField()),
                ('tour_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='adminside.tourpackage')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('package_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='adminside.packageschedule')),
            ],
        ),
        migrations.CreateModel(
            name='SchedulePhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='tour_photos/')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='adminside.schedule')),
            ],
        ),
    ]
