# Generated by Django 4.2.7 on 2025-08-12 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0009_packageschedule_schedule_schedulephoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packageschedule',
            name='schedule_title',
        ),
    ]
