# Generated by Django 4.2.7 on 2025-08-07 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuserotp',
            name='user',
        ),
    ]
