# Generated by Django 4.2.7 on 2025-08-07 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0002_remove_customuserotp_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUserOTP',
        ),
    ]
