# Generated by Django 4.2.7 on 2025-08-07 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0003_delete_customuserotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('otp', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
